-- ImNotAnAttorney Database Schema
-- Run this in Supabase SQL Editor to create tables

-- Subscribers (email list — replaces data/subscribers.json)
create table if not exists subscribers (
  id uuid default gen_random_uuid() primary key,
  email text not null unique,
  source text not null default 'lead-capture',
  unsubscribed_at timestamptz, -- CAN-SPAM: tracks when user unsubscribed
  created_at timestamptz default now() not null
);

-- Migration for existing databases:
-- ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS unsubscribed_at timestamptz;

-- Intakes (case submissions — replaces data/intakes.json)
create table if not exists intakes (
  id uuid default gen_random_uuid() primary key,
  first_name text not null,
  last_name text,
  email text not null,
  phone text,
  charge_type text not null,
  state text,
  has_attorney text,
  has_discovery text,
  services text[], -- array of selected service interests
  situation text,
  time_since_arrest text, -- month/year when arrested or charged
  arrest_circumstances text[], -- how law enforcement got involved
  incident_location text, -- where the alleged incident took place
  co_defendants text, -- was anyone else present or charged
  attorney_strategy text, -- has attorney explained defense strategy
  specific_question text, -- one specific question they need answered
  case_number text, -- optional case number for docket lookup
  court_date date, -- next court date (optional)
  plea_offered text, -- yes/no/not yet
  plea_terms text, -- conditional: plea terms if offered
  communication_frequency text, -- weekly/biweekly/monthly/rarely/never
  last_attorney_contact text, -- when they last heard from attorney
  arrest_date date, -- enables speedy trial calculation
  evidence_type text[], -- multi-select: CI, surveillance, forensic, body cam, confession, witness ID, DNA, digital/phone
  created_at timestamptz default now() not null
);

-- Orders (payment records)
create table if not exists orders (
  id uuid default gen_random_uuid() primary key,
  email text not null,
  tier text not null, -- case-decoder, intelligence-brief, x-ray, war-room, situation-room
  amount integer not null, -- cents
  status text not null default 'pending', -- pending, paid, refunded
  stripe_session_id text unique,
  stripe_payment_intent_id text,
  upgrade_credit_applied integer default 0, -- cents credited from prior purchase
  refunded_at timestamptz, -- when refund was processed
  priority_delivery boolean default false, -- priority delivery add-on purchased
  court_date date, -- client's next court date (from checkout)
  consent_timestamp timestamptz, -- when $2,497+ consent checkbox was accepted
  created_at timestamptz default now() not null,
  paid_at timestamptz
);

-- Cases (active cases linked to paid orders)
create table if not exists cases (
  id uuid default gen_random_uuid() primary key,
  order_id uuid references orders(id) not null,
  email text not null,
  tier text not null,
  status text not null default 'intake', -- intake, commenced, in-progress, review, phase_1_delivered, phase_2_delivered, delivered, refunded
  commenced_at timestamptz, -- when custom research began (refund policy trigger for $2,497+)
  intake_id uuid references intakes(id),
  file_urls text[], -- discovery document URLs in Supabase Storage
  deliverable_url text, -- URL to final report
  report_html text, -- generated report HTML content
  report_token uuid, -- unique token for report viewing URL
  generated_at timestamptz, -- when report was generated by Claude API
  delivered_at timestamptz, -- when report was delivered to customer
  reviewed_by text, -- who approved the report (operator)
  reviewed_at timestamptz, -- when report was approved
  review_reminder_sent boolean default false, -- tracks 12-hour review reminder
  charge_type text, -- charge type from linked intake
  notes text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Indexes
create index if not exists idx_orders_email on orders(email);
create index if not exists idx_orders_email_status on orders(email, status);
create index if not exists idx_orders_stripe_session on orders(stripe_session_id);
create index if not exists idx_cases_email on cases(email);
create index if not exists idx_cases_order on cases(order_id);
create index if not exists idx_cases_report_token on cases(report_token);
create index if not exists idx_cases_status on cases(status);
create index if not exists idx_intakes_email on intakes(email);

-- Row Level Security (enable for all tables)
alter table subscribers enable row level security;
alter table intakes enable row level security;
alter table orders enable row level security;
alter table cases enable row level security;

-- RLS policies: service role can do everything, anon can only insert
-- Subscribers: anon can insert (sign up for email list)
create policy "Anon can subscribe" on subscribers
  for insert to anon with check (true);

-- Intakes: anon can insert (submit case info)
create policy "Anon can submit intake" on intakes
  for insert to anon with check (true);

-- Orders/Cases: service role only (webhooks handle creation)
-- No anon access needed — Stripe webhook creates orders via admin client

-- Storage bucket for discovery files
-- Run separately: insert into storage.buckets (id, name, public) values ('discovery-files', 'discovery-files', false);
