"use client";

import { useRef, useState } from "react";
import {
  type MotionValue,
  motion,
  useScroll,
  useTransform,
  useReducedMotion,
} from "framer-motion";
import Image from "next/image";
import Link from "next/link";

/**
 * DiscoveryReveal — Real PCSO Discovery Report Images
 *
 * Renders actual redacted pages from PCSO Supplement SO22-401531/7
 * and Pinellas County Forensic Laboratory Report 23-000093.
 * Images generated by scripts/redact-discovery.py using PyMuPDF.
 *
 * Three findings are called out below each document page:
 *   1. CI phone dual attribution (page 3)
 *   2. 68.3g weight discrepancy (page 4 + lab page 1)
 *   3. Drug type mismatch (lab page 2)
 */

const findings = [
  {
    image: "/discovery/pcso-page3-ci-phone.png",
    alt: "PCSO Supplement SO22-401531/7, Page 3 — phone number (912) 380-2720 listed under both the suspect and confidential informant CI-7042",
    tag: "DUAL ATTRIBUTION \u2014 Same phone number (912) 380-2720 listed for both the suspect and the confidential informant in the same report",
    text: "The suspect\u2019s phone and the CI\u2019s phone are the same number. Same detective. Same report. Same page.",
  },
  {
    image: "/discovery/pcso-page4-weight.png",
    alt: "PCSO Supplement SO22-401531/7, Page 4 — property weight listed as 93.9 grams of MDMA at the scene",
    tag: "68.3g UNACCOUNTED \u2014 Scene: 93.9g. Lab: 25.59g. Where is the rest?",
    text: "The detective weighed 93.9 grams at the scene. The lab received and tested 25.59 grams. 68.3 grams vanished between the scene and the lab.",
  },
  {
    image: "/discovery/lab-page1-items.png",
    alt: "Pinellas County Forensic Laboratory Report 23-000093, Page 1 — lab tested items totaling 25.59 grams, identified as methamphetamine not MDMA",
    tag: "SUBSTANCE MISMATCH \u2014 Police called it MDMA. Lab found methamphetamine. Different drug, different statute, different charge.",
    text: "The detective logged \u201CMDMA (Ecstasy)\u201D at the scene. The lab\u2019s chemical analysis found methamphetamine. The charge references one substance. The evidence contains another.",
  },
  {
    image: "/discovery/lab-page2-drugtype.png",
    alt: "Pinellas County Forensic Laboratory Report 23-000093, Page 2 — Items 025-A and 026-A identified as MDMA and MDA respectively",
    tag: "FATAL VARIANCE \u2014 Items 137-139 identified as \u201CAdderall\u201D (amphetamine) by police. Lab found MDMA and MDA. Charged under wrong statute.",
    text: "Count 8 charges amphetamine trafficking under FS 893.135(1)(f)(1). The lab found MDMA/MDA \u2014 a different controlled substance under FS 893.135(1)(k). The charge is for a substance the lab says isn\u2019t there.",
  },
];

interface FindingCardProps {
  opacity?: MotionValue<number>;
  tag: string;
  children: React.ReactNode;
  animated?: boolean;
}

function FindingCard({ opacity, tag, children, animated = true }: FindingCardProps) {
  const content = (
    <div className="mt-3 rounded border-l-4 border-amber-500 bg-amber-500/10 px-4 py-3">
      <div className="text-sm text-zinc-300">{children}</div>
      <div className="mt-1.5 text-xs font-bold text-amber-400">{tag}</div>
    </div>
  );

  if (!animated || !opacity) return content;

  return <motion.div style={{ opacity }}>{content}</motion.div>;
}

export function DiscoveryReveal() {
  const shouldReduce = useReducedMotion();
  const containerRef = useRef<HTMLDivElement>(null);
  const [showAllMobile, setShowAllMobile] = useState(false);

  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start end", "end start"],
  });

  const f1Opacity = useTransform(scrollYProgress, [0.08, 0.14], [0, 1]);
  const f2Opacity = useTransform(scrollYProgress, [0.22, 0.28], [0, 1]);
  const f3Opacity = useTransform(scrollYProgress, [0.36, 0.42], [0, 1]);
  const f4Opacity = useTransform(scrollYProgress, [0.50, 0.56], [0, 1]);

  const opacities = [f1Opacity, f2Opacity, f3Opacity, f4Opacity];

  return (
    <section
      ref={shouldReduce ? undefined : containerRef}
      className="border-t border-zinc-600 px-4 py-20 section-alt"
    >
      <div className="mx-auto max-w-4xl">
        <motion.div
          initial={shouldReduce ? undefined : { opacity: 0, y: 24 }}
          whileInView={shouldReduce ? undefined : { opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.5, type: "spring", stiffness: 100, damping: 20 }}
        >
          <h2 className="font-display text-center text-2xl font-bold text-white md:text-3xl">
            What we actually found in a real case
          </h2>
          <p className="mt-3 text-center text-zinc-400">
            Real pages from real PCSO discovery. Real findings the attorney never raised.
          </p>
        </motion.div>

        <div
          className="mx-auto mt-10 max-w-2xl space-y-8"
          role="region"
          aria-label="Excerpts from real PCSO discovery reports showing critical findings: CI phone dual attribution, 68.3g weight discrepancy, and drug type mismatch"
        >
          {findings.map((f, i) => (
            <motion.div
              key={f.image}
              initial={shouldReduce ? undefined : { opacity: 0, y: 20 }}
              whileInView={shouldReduce ? undefined : { opacity: 1, y: 0 }}
              viewport={{ once: true, amount: 0.1 }}
              transition={{ duration: 0.5 }}
              className={i >= 2 && !showAllMobile ? "hidden md:block" : undefined}
            >
              <div className="overflow-hidden rounded-sm shadow-xl">
                <Image
                  src={f.image}
                  alt={f.alt}
                  width={612}
                  height={792}
                  className="w-full"
                  sizes="(max-width: 672px) 100vw, 672px"
                  quality={90}
                />
              </div>
              <FindingCard
                opacity={shouldReduce ? undefined : opacities[i]}
                tag={f.tag}
                animated={!shouldReduce}
              >
                {f.text}
              </FindingCard>
            </motion.div>
          ))}
          {!showAllMobile && (
            <button
              onClick={() => setShowAllMobile(true)}
              className="mt-4 w-full rounded-lg border border-zinc-700 py-3 text-center text-sm font-semibold text-amber-400 transition-colors hover:border-amber-500/50 md:hidden"
            >
              See 2 more findings &darr;
            </button>
          )}
        </div>

        <p className="mt-8 text-center text-sm text-zinc-400">
          He found these in his own case.{" "}
          <span className="font-semibold text-amber-400">
            We find them in yours.
          </span>
        </p>
        <div className="mt-6 text-center">
          <Link
            href="/sample"
            className="text-sm font-semibold text-amber-400 underline decoration-amber-400/50 hover:text-amber-300"
          >
            See the full sample report from this case &rarr;
          </Link>
        </div>
      </div>
    </section>
  );
}
