/**
 * blog/[slug]/page.tsx -- Individual blog post page with MDX rendering and SEO.
 *
 * Statically generated at build time via `generateStaticParams()` which enumerates
 * all post slugs from `content/blog/`.
 *
 * Page structure (top to bottom):
 *   1. Post header: date, reading time, title, excerpt, tags.
 *   2. Article schema markup (JSON-LD) for Google rich results.
 *   3. SourceIntelligence component -- attorney methodology citations based on category.
 *   4. MDX content rendered via `next-mdx-remote/rsc` (server-side, no client JS).
 *   5. Share buttons (SMS, WhatsApp, Email, Twitter/X, Facebook) -- growth loop.
 *   6. BlogCTA -- conversion CTA for Case Decoder.
 *   7. LeadCapture -- email capture for discovery checklist.
 *   8. Related posts (up to 2, same category) rendered as BlogCard components.
 *
 * SEO: Dynamic `generateMetadata()` sets per-post title, description, canonical URL,
 * and OpenGraph article metadata (type, published time, tags). Dynamic OG image is
 * generated by the sibling `opengraph-image.tsx` file.
 *
 * If the slug does not match any post, `notFound()` triggers the 404 page.
 *
 * Data source: `src/lib/blog.ts` -- reads MDX files from `content/blog/`.
 */
import { getAllPosts, getPostBySlug, getRelatedPosts } from "@/lib/blog";
import { LeadCapture } from "@/components/LeadCapture";
import { BlogCTA } from "@/components/BlogCTA";
import { BlogCard } from "@/components/BlogCard";
import { PlaybookCTA } from "@/components/PlaybookCTA";
import { SourceIntelligence, ATTORNEYS } from "@/components/SourceIntelligence";
import { TLDRBox } from "@/components/TLDRBox";
import { BlogInlineCapture } from "@/components/BlogInlineCapture";
import { MDXErrorBoundary } from "@/components/MDXErrorBoundary";
import { FadeInUp } from "@/components/motion/FadeInUp";
import { StaggerContainer, StaggerItem } from "@/components/motion/StaggerContainer";
import { SITE_URL } from "@/lib/site";
import { MDXRemote } from "next-mdx-remote/rsc";
import { notFound } from "next/navigation";
import type { Metadata } from "next";

const CATEGORY_LABELS: Record<string, string> = {
  dui: "DUI Defense",
  "drug-cases": "Drug Defense",
  "white-collar": "White Collar Defense",
  "general-defense": "Criminal Defense",
};

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  const posts = getAllPosts();
  return posts.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) return {};

  return {
    title: post.title,
    description: post.excerpt,
    alternates: {
      canonical: `${SITE_URL}/blog/${slug}`,
    },
    openGraph: {
      type: "article",
      title: post.title,
      description: post.excerpt,
      url: `${SITE_URL}/blog/${slug}`,
      publishedTime: post.date,
      tags: post.tags,
    },
  };
}

export default async function BlogPostPage({ params }: PageProps) {
  const { slug } = await params;
  const post = getPostBySlug(slug);

  if (!post) notFound();

  const related = getRelatedPosts(slug);

  return (
    <article className="px-4 py-16">
      <div className="mx-auto max-w-3xl">
        {/* Header */}
        <div className="mb-8">
          <div className="mb-4 flex items-center gap-3">
            <time dateTime={new Date(post.date).toISOString()} className="text-sm text-zinc-400">{post.date}</time>
            <span className="text-sm text-zinc-400">&bull;</span>
            <span className="text-sm text-zinc-400">{post.readingTime}</span>
          </div>
          <h1 className="font-display text-3xl font-bold leading-tight text-white md:text-4xl">
            {post.title}
          </h1>
          <p className="mt-4 text-lg text-zinc-400">{post.excerpt}</p>
          <div className="mt-4 flex flex-wrap gap-2">
            {post.tags.map((tag) => (
              <span
                key={tag}
                className="rounded-full bg-zinc-800 px-3 py-1 text-xs text-zinc-400"
              >
                {tag}
              </span>
            ))}
          </div>
        </div>

        {/* BreadcrumbList schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "BreadcrumbList",
              itemListElement: [
                {
                  "@type": "ListItem",
                  position: 1,
                  name: "Home",
                  item: SITE_URL,
                },
                {
                  "@type": "ListItem",
                  position: 2,
                  name: "Blog",
                  item: `${SITE_URL}/blog`,
                },
                {
                  "@type": "ListItem",
                  position: 3,
                  name: post.title,
                },
              ],
            }),
          }}
        />

        {/* Article schema markup */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Article",
              headline: post.title,
              description: post.excerpt,
              datePublished: post.date,
              dateModified: post.lastModified || post.date,
              url: `${SITE_URL}/blog/${slug}`,
              mainEntityOfPage: {
                "@type": "WebPage",
                "@id": `${SITE_URL}/blog/${slug}`,
              },
              author: { "@type": "Organization", "@id": `${SITE_URL}/#organization` },
              publisher: { "@type": "Organization", "@id": `${SITE_URL}/#organization` },
              image: `${SITE_URL}/blog/${slug}/opengraph-image`,
              keywords: post.tags.join(", "),
              articleSection:
                CATEGORY_LABELS[post.category] || "Criminal Defense",
              mentions: (
                ATTORNEYS[post.category] || ATTORNEYS["general-defense"]
              ).map((a) => ({
                "@type": "Person",
                name: a.name,
              })),
            }),
          }}
        />

        {/* FAQPage schema (if post has FAQs in frontmatter) */}
        {post.faqs.length > 0 && (
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({
                "@context": "https://schema.org",
                "@type": "FAQPage",
                mainEntity: post.faqs.map((faq) => ({
                  "@type": "Question",
                  name: faq.q,
                  acceptedAnswer: { "@type": "Answer", text: faq.a },
                })),
              }),
            }}
          />
        )}

        {/* Source Intelligence */}
        <SourceIntelligence category={post.category || "general-defense"} />

        {/* Content */}
        <MDXErrorBoundary>
        <div className="prose prose-invert prose-amber max-w-none prose-headings:text-white prose-p:text-zinc-300 prose-a:text-amber-400 prose-strong:text-white prose-li:text-zinc-300">
          <MDXRemote source={post.content} components={{ TLDRBox }} />
        </div>
        </MDXErrorBoundary>

        {/* Mid-article lead capture — category-specific checklist */}
        <BlogInlineCapture category={post.category || "general-defense"} />

        {/* Share — growth loop */}
        <FadeInUp>
        <div className="mt-12 rounded-xl border border-amber-500/20 bg-amber-500/5 p-6">
          <p className="text-sm font-bold text-white">
            Know someone facing charges? Send them this.
          </p>
          <p className="mt-1 text-xs text-zinc-400">
            Most defendants don&apos;t know they can hold their attorney accountable. Share this with someone who needs it.
          </p>
          <StaggerContainer className="mt-4 flex flex-wrap gap-3">
            <StaggerItem>
            <a
              href={`sms:?body=${encodeURIComponent(`Read this — it might help with your case: ${SITE_URL}/blog/${slug}`)}`}
              className="rounded-lg bg-zinc-800 px-4 py-2 text-sm text-white transition-colors hover:bg-zinc-700"
              aria-label="Share via text message"
            >
              📱 Text
            </a>
            </StaggerItem>
            <StaggerItem>
            <a
              href={`https://wa.me/?text=${encodeURIComponent(`${post.title} ${SITE_URL}/blog/${slug}`)}`}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-lg bg-zinc-800 px-4 py-2 text-sm text-white transition-colors hover:bg-zinc-700"
              aria-label="Share via WhatsApp"
            >
              WhatsApp
            </a>
            </StaggerItem>
            <StaggerItem>
            <a
              href={`mailto:?subject=${encodeURIComponent(`This might help — ${post.title}`)}&body=${encodeURIComponent(`I thought this might be useful for your case:\n\n${post.title}\n${SITE_URL}/blog/${slug}\n\nIt covers questions you should be asking your attorney.`)}`}
              className="rounded-lg bg-zinc-800 px-4 py-2 text-sm text-white transition-colors hover:bg-zinc-700"
              aria-label="Share via email"
            >
              ✉️ Email
            </a>
            </StaggerItem>
            <StaggerItem>
            <a
              href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(post.title)}&url=${encodeURIComponent(`${SITE_URL}/blog/${slug}`)}`}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-lg bg-zinc-800 px-4 py-2 text-sm text-white transition-colors hover:bg-zinc-700"
              aria-label="Share on Twitter / X"
            >
              𝕏 Twitter
            </a>
            </StaggerItem>
            <StaggerItem>
            <a
              href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(`${SITE_URL}/blog/${slug}`)}`}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-lg bg-zinc-800 px-4 py-2 text-sm text-white transition-colors hover:bg-zinc-700"
              aria-label="Share on Facebook"
            >
              Facebook
            </a>
            </StaggerItem>
          </StaggerContainer>
        </div>
        </FadeInUp>

        {/* Playbook CTA — shown above BlogCTA for DUI posts */}
        {post.category === "dui" && (
          <div className="mt-12">
            <PlaybookCTA />
          </div>
        )}

        {/* Service CTA */}
        <div className="mt-12">
          <BlogCTA category={post.category} />
        </div>

        {/* Lead Capture */}
        <div className="mt-8">
          <LeadCapture />
        </div>

        {/* Related Posts */}
        {related.length > 0 && (
          <FadeInUp>
          <div className="mt-16">
            <h2 className="font-display mb-6 text-xl font-bold text-white">
              Related Articles
            </h2>
            <StaggerContainer className="grid gap-6 md:grid-cols-2">
              {related.map((rp) => (
                <StaggerItem key={rp.slug}>
                <BlogCard
                  title={rp.title}
                  excerpt={rp.excerpt}
                  slug={rp.slug}
                  date={rp.date}
                  tags={rp.tags}
                  readingTime={rp.readingTime}
                />
                </StaggerItem>
              ))}
            </StaggerContainer>
          </div>
          </FadeInUp>
        )}
      </div>
    </article>
  );
}
