/**
 * blog/[slug]/page.tsx -- Individual blog post page with MDX rendering and SEO.
 *
 * Statically generated at build time via `generateStaticParams()` which enumerates
 * all post slugs from `content/blog/`.
 *
 * Page structure (top to bottom):
 *   1. Post header: date, reading time, title, excerpt, tags.
 *   2. Article schema markup (JSON-LD) for Google rich results.
 *   3. SourceIntelligence component -- attorney methodology citations based on category.
 *   4. MDX content rendered via `next-mdx-remote/rsc` (server-side, no client JS).
 *   5. Share buttons (SMS, WhatsApp, Email, Twitter/X, Facebook) -- growth loop.
 *   6. BlogCTA -- conversion CTA for Case Decoder.
 *   7. Score CTA -- free defense quiz link to /score.
 *   8. Related posts (up to 2, same category) rendered as BlogCard components.
 *
 * SEO: Dynamic `generateMetadata()` sets per-post title, description, canonical URL,
 * and OpenGraph article metadata (type, published time, tags). Dynamic OG image is
 * generated by the sibling `opengraph-image.tsx` file.
 *
 * If the slug does not match any post, `notFound()` triggers the 404 page.
 *
 * Data source: `src/lib/blog.ts` -- reads MDX files from `content/blog/`.
 */
import Link from "next/link";
import { getAllPosts, getPostBySlug, getRelatedPosts } from "@/lib/blog";
import { BlogCTA } from "@/components/BlogCTA";
import { PillarCTA } from "@/components/blog/PillarCTA";
import { BlogCard } from "@/components/BlogCard";
import { PlaybookCTA } from "@/components/PlaybookCTA";
import { SourceIntelligence, ATTORNEYS } from "@/components/SourceIntelligence";
import { TLDRBox } from "@/components/TLDRBox";
import { BlogInlineCapture } from "@/components/BlogInlineCapture";
import { MDXErrorBoundary } from "@/components/MDXErrorBoundary";
import { ShareButtons } from "@/components/ShareButtons";
import { FadeInUp } from "@/components/motion/FadeInUp";
import { StaggerContainer, StaggerItem } from "@/components/motion/StaggerContainer";
import { SITE_URL } from "@/lib/site";
import { getArticleAboutEntities, getArticleCitations } from "@/lib/schema";
import { MDXRemote } from "next-mdx-remote/rsc";
import { notFound } from "next/navigation";
import type { Metadata } from "next";

const CATEGORY_LABELS: Record<string, string> = {
  dui: "DUI Defense",
  "drug-cases": "Drug Defense",
  "white-collar": "White Collar Defense",
  "general-defense": "Criminal Defense",
};

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
  const posts = getAllPosts();
  return posts.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) return {};

  return {
    title: post.title,
    description: post.excerpt,
    alternates: {
      canonical: `${SITE_URL}/blog/${slug}`,
    },
    openGraph: {
      type: "article",
      title: post.title,
      description: post.excerpt,
      url: `${SITE_URL}/blog/${slug}`,
      publishedTime: post.date,
      tags: post.tags,
    },
  };
}

export default async function BlogPostPage({ params }: PageProps) {
  const { slug } = await params;
  const post = getPostBySlug(slug);

  if (!post) notFound();

  const related = getRelatedPosts(slug);

  return (
    <article className="px-4 py-16">
      <div className="mx-auto max-w-3xl">
        {/* Header */}
        <div className="mb-8">
          <div className="mb-4 flex flex-wrap items-center gap-3 text-sm text-zinc-400">
            <span>By ImNotAnAttorney</span>
            <span>&bull;</span>
            <time dateTime={new Date(post.date).toISOString()}>{post.date}</time>
            {post.lastModified && post.lastModified !== post.date && (
              <>
                <span>&bull;</span>
                <span>Updated <time dateTime={new Date(post.lastModified).toISOString()}>{post.lastModified}</time></span>
              </>
            )}
            <span>&bull;</span>
            <span>{post.readingTime}</span>
          </div>
          <h1 className="font-display text-3xl font-bold leading-tight text-white md:text-4xl">
            {post.title}
          </h1>
          <p className="mt-4 text-lg text-zinc-400">{post.excerpt}</p>
          <div className="mt-4 flex flex-wrap gap-2">
            {post.tags.map((tag) => (
              <Link
                key={tag}
                href={`/blog?category=${encodeURIComponent(post.category)}`}
                className="rounded-full bg-zinc-800 px-3 py-1 text-xs text-zinc-400 transition-colors hover:bg-zinc-700 hover:text-zinc-200"
              >
                {tag}
              </Link>
            ))}
          </div>
        </div>

        {/* BreadcrumbList schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "BreadcrumbList",
              itemListElement: [
                {
                  "@type": "ListItem",
                  position: 1,
                  name: "Home",
                  item: SITE_URL,
                },
                {
                  "@type": "ListItem",
                  position: 2,
                  name: "Blog",
                  item: `${SITE_URL}/blog`,
                },
                {
                  "@type": "ListItem",
                  position: 3,
                  name: post.title,
                  item: `${SITE_URL}/blog/${slug}`,
                },
              ],
            }),
          }}
        />

        {/* Article schema markup */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Article",
              "@id": `${SITE_URL}/blog/${slug}#article`,
              headline: post.title,
              description: post.excerpt,
              datePublished: post.date,
              dateModified: post.lastModified || post.date,
              url: `${SITE_URL}/blog/${slug}`,
              mainEntityOfPage: {
                "@type": "WebPage",
                "@id": `${SITE_URL}/blog/${slug}`,
              },
              author: {
                "@type": "Organization",
                "@id": `${SITE_URL}/#organization`,
                name: "ImNotAnAttorney",
                url: SITE_URL,
              },
              publisher: { "@type": "Organization", "@id": `${SITE_URL}/#organization` },
              wordCount: post.content.split(/\s+/).length,
              image: `${SITE_URL}/blog/${slug}/opengraph-image`,
              keywords: post.tags.join(", "),
              articleSection:
                CATEGORY_LABELS[post.category] || "Criminal Defense",
              educationalLevel: "beginner",
              audience: { "@type": "Audience", audienceType: "criminal defendant" },
              speakable: {
                "@type": "SpeakableSpecification",
                cssSelector: [".tldr-box", "article h2:first-of-type + p"],
              },
              ...(() => {
                const aboutEntities = getArticleAboutEntities(post.category, post.tags);
                return aboutEntities.length > 0 ? { about: aboutEntities } : {};
              })(),
              ...(() => {
                const citations = getArticleCitations(slug);
                return citations ? { citation: citations } : {};
              })(),
              ...(slug === "what-500-pages-of-drug-trafficking-discovery-contained"
                ? {
                    isBasedOn: {
                      "@type": "CreativeWork",
                      name: "Florida Drug Trafficking Discovery Documents (Case Study)",
                      description: "500 pages of discovery materials reviewed 2025",
                    },
                  }
                : {}),
              mentions: (
                ATTORNEYS[post.category] || ATTORNEYS["general-defense"]
              ).map((a) => ({
                "@type": "Person",
                name: a.name,
              })),
            }),
          }}
        />

        {/* FAQPage schema (if post has FAQs in frontmatter) */}
        {post.faqs.length > 0 && (
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({
                "@context": "https://schema.org",
                "@type": "FAQPage",
                isPartOf: { "@id": `${SITE_URL}/blog/${slug}#article` },
                mainEntity: post.faqs.map((faq) => ({
                  "@type": "Question",
                  name: faq.q,
                  isPartOf: { "@id": `${SITE_URL}/blog/${slug}#article` },
                  acceptedAnswer: { "@type": "Answer", text: faq.a },
                })),
              }),
            }}
          />
        )}

        {/* HowTo schema (if post has howToSteps in frontmatter) */}
        {post.howToSteps.length > 0 && (
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({
                "@context": "https://schema.org",
                "@type": "HowTo",
                name: post.title,
                description: post.excerpt,
                step: post.howToSteps.map((step, i) => ({
                  "@type": "HowToStep",
                  position: i + 1,
                  name: step.name,
                  text: step.text,
                })),
              }),
            }}
          />
        )}

        {/* Source Intelligence */}
        <SourceIntelligence category={post.category || "general-defense"} />

        {/* Content */}
        <MDXErrorBoundary>
        <div className="prose prose-invert prose-amber max-w-none prose-headings:text-white prose-p:text-zinc-300 prose-a:text-amber-400 prose-strong:text-white prose-li:text-zinc-300">
          <MDXRemote source={post.content} components={{ TLDRBox }} />
        </div>
        </MDXErrorBoundary>

        {/* Mid-article lead capture, category-specific checklist */}
        <BlogInlineCapture category={post.category || "general-defense"} slug={slug} />

        {/* Share, growth loop */}
        <ShareButtons url={`/blog/${slug}`} title={post.title} />

        {/* Playbook CTA, shown above BlogCTA for DUI posts */}
        {post.category === "dui" && (
          <div className="mt-12">
            <PlaybookCTA slug={slug} />
          </div>
        )}

        {/* Service CTA, pillar-aware when available, fallback to generic */}
        <div className="mt-12">
          {post.pillarSlug ? (
            <PillarCTA
              pillarSlug={post.pillarSlug}
              linkedProducts={post.linkedProducts}
              freeEntryPoint={post.freeEntryPoint}
              ctaTier={post.ctaTier}
              articleSlug={slug}
            />
          ) : (
            <BlogCTA category={post.category} slug={slug} />
          )}
        </div>

        {/* Score CTA, Free defense quiz */}
        <div className="mt-8 rounded-xl border border-amber-500/30 bg-amber-500/5 p-6 text-center">
          <p className="text-sm font-bold text-white">
            Want to see how your defense measures up?
          </p>
          <p className="mt-1 text-sm text-zinc-400">
            10 questions. 60 seconds. Free, no email required to start.
          </p>
          <Link
            href={`/score?ref=blog-${slug}`}
            className="mt-4 inline-block rounded-lg bg-amber-500 px-6 py-3 text-sm font-bold text-black transition-all hover:scale-[1.02] focus-visible:scale-[1.02] hover:bg-amber-400 hover:shadow-lg hover:shadow-amber-500/20"
          >
            Take the Defense Milestone Score, Free
          </Link>
        </div>

        {/* Related Posts */}
        {related.length > 0 && (
          <FadeInUp>
          <div className="mt-16">
            <h2 className="font-display mb-6 text-xl font-bold text-white">
              Related Articles
            </h2>
            <StaggerContainer className="grid gap-6 md:grid-cols-2">
              {related.map((rp) => (
                <StaggerItem key={rp.slug}>
                <BlogCard
                  title={rp.title}
                  excerpt={rp.excerpt}
                  slug={rp.slug}
                  date={rp.date}
                  tags={rp.tags}
                  readingTime={rp.readingTime}
                />
                </StaggerItem>
              ))}
            </StaggerContainer>
          </div>
          </FadeInUp>
        )}
      </div>
    </article>
  );
}
