/**
 * @file /api/webhooks/engine/delivery — Engine delivery notification webhook
 *
 * Pipeline position: Called by the ImNotAnAttorney-engine's delivery_notification
 * worker when a discovery-tier report (X-Ray, War Room, Situation Room) is ready,
 * OR when the docket_monitor worker has a weekly War Room update to deliver.
 * Engine-tier reports are generated by the 29-worker backend pipeline, not by the
 * Supabase Edge Function used for CD/IB.
 *
 * Payload from the engine worker:
 *   {
 *     type?:        "delivery" | "update"  — defaults to "delivery" if omitted
 *     caseId:       string   — INNA case UUID
 *     orderId:      string   — INNA order UUID
 *     tier:         string   — tier slug (e.g. "x-ray", "war-room", "situation-room")
 *     downloadUrls: string[] — one or more signed/absolute URLs for the report files
 *     deliveredAt:  string   — ISO timestamp from the engine
 *     updateSummary?: string — plain-text summary of weekly update (type: "update" only)
 *   }
 *
 * Flow (type: "delivery" — initial delivery):
 *   1. Authenticate request (OPERATOR_SECRET bearer token — same auth as /api/generate/*)
 *   2. Load order + case to get customer email and tier context
 *   3. Atomically update case + order status to "delivered" (or "monitoring" for War Room)
 *   4. Send tier-specific delivery email to customer with all download URLs
 *   5. Record post-purchase drip sequence start (prevents cron double-delivery)
 *   6. Return { success: true }
 *
 * Flow (type: "update" — War Room weekly / Situation Room update):
 *   1. Authenticate request
 *   2. Load case to get customer email
 *   3. Do NOT change case status (already delivered/monitoring)
 *   4. Send update email with new download URLs and updateSummary
 *   5. Return { success: true }
 *
 * Auth: Bearer token against OPERATOR_SECRET (same guard used by all /api/generate/* routes).
 * The engine worker should include: Authorization: Bearer <OPERATOR_SECRET>
 *
 * Error strategy: Non-critical failures (email, drip) are logged but do NOT fail the
 * response — the engine worker should not retry just because an email bounced.
 * Critical failures (case not found, status update failed) return 4xx/5xx so the
 * engine can retry.
 */

import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendEmailWithOperatorAlert, escapeHtml } from "@/lib/email";
import type { EmailLogContext } from "@/lib/email";
import { caseThreadId } from "@/lib/site";
import { requireOperatorSecret } from "@/lib/auth/guards";
import { TIER_CORE, tierDisplayName, upgradePrice, isValidTier } from "@/lib/tiers";

/** Fallback operator email if OPERATOR_EMAIL env var is not set. */
const OPERATOR_EMAIL =
  process.env.OPERATOR_EMAIL || "rahim0kapadia@gmail.com";

// ================================================================
// POST: Engine delivery notification
// ================================================================
export async function POST(req: NextRequest) {
  // ──────────────────────────────────────────────────────────────
  // AUTH: Bearer token validation (same pattern as /api/generate/*)
  // ──────────────────────────────────────────────────────────────
  const auth = requireOperatorSecret(req);
  if (!auth.authorized) return auth.error;

  // ──────────────────────────────────────────────────────────────
  // INPUT VALIDATION
  // ──────────────────────────────────────────────────────────────
  let body: {
    type?: "delivery" | "update";
    caseId: string;
    orderId: string;
    tier: string;
    downloadUrls: string[];
    deliveredAt: string;
    updateSummary?: string;
  };

  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { caseId, orderId, tier, downloadUrls, deliveredAt, updateSummary } = body;
  // Default to "delivery" if type is not provided (backward compatibility)
  const deliveryType = body.type ?? "delivery";

  if (!caseId) return NextResponse.json({ error: "caseId required" }, { status: 400 });
  if (!tier) return NextResponse.json({ error: "tier required" }, { status: 400 });
  if (!Array.isArray(downloadUrls) || downloadUrls.length === 0) {
    return NextResponse.json({ error: "downloadUrls must be a non-empty array" }, { status: 400 });
  }
  // orderId is required for initial delivery; optional for updates
  if (deliveryType === "delivery" && !orderId) {
    return NextResponse.json({ error: "orderId required for delivery type" }, { status: 400 });
  }

  const supabase = createAdminClient();
  const now = deliveredAt || new Date().toISOString();

  // ================================================================
  // TYPE: "update" — War Room / Situation Room weekly update delivery
  // ================================================================
  // Does NOT change case status. Sends an update email only.
  if (deliveryType === "update") {
    const { data: updateCaseData, error: updateCaseError } = await supabase
      .from("cases")
      .select("id, email, status, tier, intake_id")
      .eq("id", caseId)
      .single();

    if (updateCaseError || !updateCaseData) {
      console.error("[Engine-Delivery] Case not found for update:", caseId, updateCaseError);
      return NextResponse.json({ error: "Case not found" }, { status: 404 });
    }

    const origin = process.env.NEXT_PUBLIC_SITE_URL || "https://imnotanattorney.com";
    const tierName = tierDisplayName(tier);

    // Get customer first name from intake
    let updateFirstName = "there";
    if (updateCaseData.intake_id) {
      const { data: updateIntake } = await supabase
        .from("intakes")
        .select("first_name")
        .eq("id", updateCaseData.intake_id)
        .single();
      if (updateIntake?.first_name) updateFirstName = updateIntake.first_name;
    }

    const updateLinksHtml = downloadUrls
      .map((url, idx) => {
        const label =
          downloadUrls.length === 1
            ? "Download Update Report"
            : `Download Update (Part ${idx + 1})`;
        return `<p style="margin: 8px 0;"><a href="${escapeHtml(url)}" style="display: inline-block; padding: 12px 24px; background: #F59E0B; color: black; font-weight: bold; text-decoration: none; border-radius: 8px;">${label}</a></p>`;
      })
      .join("");

    const updateSummaryHtml = updateSummary
      ? `<div style="background: #1C1917; padding: 20px; border-radius: 12px; margin: 20px 0; border-left: 4px solid #F59E0B;">
          <p style="margin: 0; color: white; font-weight: bold;">This Week's Findings</p>
          <p style="margin: 8px 0 0; color: #D4D4D8; white-space: pre-line;">${escapeHtml(updateSummary)}</p>
        </div>`
      : "";

    const updateLogContext: EmailLogContext = {
      category: "delivery",
      case_id: caseId,
      order_id: orderId || undefined,
      metadata: { tier, source: "engine-update-webhook" },
    };

    const updateEmailResult = await sendEmailWithOperatorAlert(
      {
        to: updateCaseData.email,
        subject: `Your ${tierName} — Weekly Update Ready`,
        unsubscribeEmail: updateCaseData.email,
        threadingHeaders: {
          inReplyTo: caseThreadId(caseId),
          references: caseThreadId(caseId),
        },
        html: `
          <h1 style="color: #F59E0B;">Weekly Update Ready</h1>
          <p>Hi ${escapeHtml(updateFirstName)},</p>
          <p>Your ${escapeHtml(tierName)} weekly update is in. New findings are below.</p>
          ${updateLinksHtml}
          ${updateSummaryHtml}
          <p style="margin-top: 32px; color: #71717A; font-size: 14px;">Reply to this email with any questions or new documents to include in the next update.</p>
        `,
      },
      `Engine weekly update email for case ${caseId} (${tier})`,
      updateLogContext
    );

    if (!updateEmailResult.success) {
      console.error(`[Engine-Delivery] Update email failed for case ${caseId}:`, updateEmailResult.error);
    }

    return NextResponse.json({
      success: true,
      caseId,
      tier,
      type: "update",
      emailDelivered: updateEmailResult.success,
      message: updateEmailResult.success
        ? "Update email sent to customer"
        : "Update email failed — operator alerted",
    });
  }

  // ──────────────────────────────────────────────────────────────
  // LOAD CASE + ORDER: Get customer email and current status
  // ──────────────────────────────────────────────────────────────
  const { data: caseData, error: caseError } = await supabase
    .from("cases")
    .select("id, email, status, tier, intake_id")
    .eq("id", caseId)
    .single();

  if (caseError || !caseData) {
    console.error("[Engine-Delivery] Case not found:", caseId, caseError);
    return NextResponse.json({ error: "Case not found" }, { status: 404 });
  }

  // Idempotency: if already delivered or monitoring, return success without re-processing
  if (caseData.status === "delivered" || caseData.status === "monitoring") {
    console.warn(`[Engine-Delivery] Case ${caseId} already in terminal state (${caseData.status}) — skipping`);
    return NextResponse.json({
      success: true,
      skipped: true,
      message: `Case already ${caseData.status}`,
    });
  }

  // ──────────────────────────────────────────────────────────────
  // ATOMIC STATUS UPDATE: case + order → "delivered" or "monitoring"
  // ──────────────────────────────────────────────────────────────
  // War Room transitions to "monitoring" after initial delivery —
  // weekly docket_monitor updates continue and use type:"update".
  // All other tiers transition to "delivered" (terminal).
  const primaryUrl = downloadUrls[0];
  const postDeliveryStatus = (tier === "war-room" || tier === "situation-room")
    ? "monitoring"
    : "delivered";

  const { data: caseGuard } = await supabase
    .from("cases")
    .update({
      status: postDeliveryStatus,
      delivered_at: now,
      deliverable_url: primaryUrl,
      updated_at: new Date().toISOString(),
    })
    .eq("id", caseId)
    .not("status", "in", '("delivered","monitoring")') // Atomic guard — only one caller can win
    .select("id")
    .single();

  if (!caseGuard) {
    // Either already delivered/monitoring (race) or unexpected state — log, don't block
    console.warn(`[Engine-Delivery] Case status update skipped for ${caseId} (already in terminal state or race condition)`);
  }

  // Update order status to match case status
  await supabase
    .from("orders")
    .update({ status: postDeliveryStatus, updated_at: new Date().toISOString() })
    .eq("id", orderId)
    .not("status", "in", '("delivered","monitoring")');

  // ──────────────────────────────────────────────────────────────
  // CUSTOMER EMAIL: Tier-specific delivery email with download URLs
  // ──────────────────────────────────────────────────────────────
  const origin = process.env.NEXT_PUBLIC_SITE_URL || "https://imnotanattorney.com";
  const tierName = tierDisplayName(tier);

  // Get customer first name from intake
  let firstName = "there";
  if (caseData.intake_id) {
    const { data: intake } = await supabase
      .from("intakes")
      .select("first_name")
      .eq("id", caseData.intake_id)
      .single();
    if (intake?.first_name) firstName = intake.first_name;
  }

  // Build download URL list HTML
  const downloadLinksHtml = downloadUrls
    .map((url, idx) => {
      const label =
        downloadUrls.length === 1
          ? "Download Your Report"
          : `Download Report${downloadUrls.length > 1 ? ` (Part ${idx + 1})` : ""}`;
      return `<p style="margin: 8px 0;"><a href="${escapeHtml(url)}" style="display: inline-block; padding: 12px 24px; background: #F59E0B; color: black; font-weight: bold; text-decoration: none; border-radius: 8px;">${label}</a></p>`;
    })
    .join("");

  // Tier-specific instructions and upgrade CTA
  let instructionsHtml = "";
  let upgradeHtml = "";

  if (tier === "x-ray") {
    instructionsHtml = `
      <div style="background: #1C1917; padding: 24px; border-radius: 12px; margin: 24px 0; border-left: 4px solid #F59E0B;">
        <p style="margin: 0; color: white; font-weight: bold;">How to use your X-Ray Analysis:</p>
        <ol style="color: #D4D4D8; padding-left: 20px; margin-top: 12px;">
          <li style="margin-bottom: 8px;"><strong style="color: white;">Read the Executive Summary first</strong> — your case at a glance, one page</li>
          <li style="margin-bottom: 8px;"><strong style="color: white;">Hand page 2 (Top 3 Findings) to your attorney</strong> — these are the highest-leverage issues</li>
          <li style="margin-bottom: 8px;"><strong style="color: white;">Use the "If You Only Have 15 Minutes" question list</strong> at your next meeting</li>
          <li style="margin-bottom: 8px;"><strong style="color: white;">Review the Red Flags section carefully</strong> — these are where evidence problems live</li>
        </ol>
      </div>`;
    const upgradeCost = isValidTier(tier) ? upgradePrice(tier) : null;
    upgradeHtml = upgradeCost
      ? `<div style="background: #1C1917; padding: 16px; border-radius: 8px; margin-top: 24px;">
          <p style="margin: 0; color: #F59E0B; font-weight: bold;">Need deeper ongoing investigation?</p>
          <p style="margin: 8px 0 0; color: #D4D4D8;">Your ${isValidTier(tier) ? TIER_CORE[tier].priceDisplay : ""} is credited toward ${tierDisplayName("war-room")} (${TIER_CORE["war-room"].priceDisplay}). Pay only ${upgradeCost}. Witness dossiers, judge intelligence, and weekly updates. <a href="${origin}/services#war-room" style="color: #F59E0B;">Learn more</a></p>
        </div>`
      : "";
  } else if (tier === "war-room") {
    instructionsHtml = `
      <div style="background: #1C1917; padding: 24px; border-radius: 12px; margin: 24px 0; border-left: 4px solid #F59E0B;">
        <p style="margin: 0; color: white; font-weight: bold;">Your War Room package is ready:</p>
        <ol style="color: #D4D4D8; padding-left: 20px; margin-top: 12px;">
          <li style="margin-bottom: 8px;"><strong style="color: white;">Download all report files</strong> — they are linked above</li>
          <li style="margin-bottom: 8px;"><strong style="color: white;">Review your Judge Intelligence Profile</strong> — sentencing patterns, tendencies, motion preferences</li>
          <li style="margin-bottom: 8px;"><strong style="color: white;">Review each Witness Dossier</strong> — background, credibility vulnerabilities, cross-exam questions</li>
          <li style="margin-bottom: 8px;"><strong style="color: white;">Weekly updates begin now</strong> — you'll hear from us each week as new findings emerge</li>
        </ol>
      </div>`;
    const upgradeCost = upgradePrice("war-room");
    upgradeHtml = upgradeCost
      ? `<div style="background: #1C1917; padding: 16px; border-radius: 8px; margin-top: 24px;">
          <p style="margin: 0; color: #F59E0B; font-weight: bold;">Trial approaching?</p>
          <p style="margin: 8px 0 0; color: #D4D4D8;">Upgrade to The Situation Room for 24-48hr priority turnaround and Trial Intelligence Operations. Pay only ${upgradeCost}. <a href="${origin}/services#situation-room" style="color: #F59E0B;">Learn more</a></p>
        </div>`
      : "";
  } else if (tier === "situation-room") {
    instructionsHtml = `
      <div style="background: #1C1917; padding: 24px; border-radius: 12px; margin: 24px 0; border-left: 4px solid #F59E0B;">
        <p style="margin: 0; color: white; font-weight: bold;">Your Situation Room package is ready:</p>
        <ol style="color: #D4D4D8; padding-left: 20px; margin-top: 12px;">
          <li style="margin-bottom: 8px;"><strong style="color: white;">Download all deliverables</strong> — linked above</li>
          <li style="margin-bottom: 8px;"><strong style="color: white;">24-48hr priority turnaround</strong> is now active on all updates</li>
          <li style="margin-bottom: 8px;"><strong style="color: white;">Trial Intelligence Operations activate</strong> when your trial date is confirmed — reply to this email with your trial date</li>
          <li style="margin-bottom: 8px;"><strong style="color: white;">Reply to this email</strong> any time you need priority analysis or have new documents</li>
        </ol>
      </div>`;
    upgradeHtml = ""; // Top tier — no upgrade
  } else {
    // Generic fallback for any other tier
    instructionsHtml = `
      <div style="background: #1C1917; padding: 24px; border-radius: 12px; margin: 24px 0; border-left: 4px solid #F59E0B;">
        <p style="margin: 0; color: white; font-weight: bold;">How to use your ${escapeHtml(tierName)}:</p>
        <p style="margin: 8px 0 0; color: #D4D4D8;">Download your report using the link above. Review the findings with your attorney at your earliest opportunity.</p>
      </div>`;
    upgradeHtml = "";
  }

  const deliveryLogContext: EmailLogContext = {
    category: "delivery",
    case_id: caseId,
    order_id: orderId,
    metadata: { tier, source: "engine-delivery-webhook" },
  };

  const emailResult = await sendEmailWithOperatorAlert(
    {
      to: caseData.email,
      subject: `Your ${tierName} is Ready`,
      unsubscribeEmail: caseData.email,
      threadingHeaders: {
        inReplyTo: caseThreadId(caseId),
        references: caseThreadId(caseId),
      },
      html: `
        <h1 style="color: #F59E0B;">Your ${escapeHtml(tierName)} is Ready</h1>
        <p>Hi ${escapeHtml(firstName)},</p>
        <p>Your personalized ${escapeHtml(tierName)} package is complete. Use the link${downloadUrls.length > 1 ? "s" : ""} below to access your report${downloadUrls.length > 1 ? "s" : ""}.</p>
        ${downloadLinksHtml}
        ${instructionsHtml}
        ${upgradeHtml}
        <p style="margin-top: 32px; color: #71717A; font-size: 14px;">Reply to this email with any questions. We're here throughout your case.</p>
      `,
    },
    `Engine delivery email for case ${caseId} (${tier})`,
    deliveryLogContext
  );

  if (!emailResult.success) {
    console.error(`[Engine-Delivery] Delivery email failed for case ${caseId}:`, emailResult.error);
  }

  // ──────────────────────────────────────────────────────────────
  // DRIP: Record delivery to prevent cron double-sending
  // ──────────────────────────────────────────────────────────────
  // Upsert subscriber record (non-subscriber buyers need one for the FK).
  // Then mark the day-0 delivery drip email as sent so the cron skips it.
  try {
    const { data: subData } = await supabase
      .from("subscribers")
      .upsert(
        { email: caseData.email.toLowerCase(), source: `purchase-${tier}` },
        { onConflict: "email" }
      )
      .select("id")
      .single();

    if (subData?.id) {
      const dripKey = `post_${tier.split("-").join("_")}_delivery`;
      await supabase.from("drip_emails").upsert(
        { subscriber_id: subData.id, email_key: dripKey },
        { onConflict: "subscriber_id,email_key" }
      );
    }
  } catch (err) {
    // Non-critical — log but don't fail the response
    console.error("[Engine-Delivery] Failed to record drip:", err);
  }

  // ──────────────────────────────────────────────────────────────
  // RESPONSE
  // ──────────────────────────────────────────────────────────────
  return NextResponse.json({
    success: true,
    caseId,
    orderId,
    tier,
    emailDelivered: emailResult.success,
    message: emailResult.success
      ? "Delivery recorded and email sent to customer"
      : "Delivery recorded but email failed — operator alerted",
  });
}
