/**
 * Enrichment & Missing States Script
 *
 * Generates missing jurisdiction data (ID, SC) and enriches existing statutes
 * with prosecution/defense strategic analysis.
 *
 * SAFETY: Case law is NEVER generated by this script. Case law MUST come from
 * verified sources (CourtListener API) via scripts/classify-case-law.mjs.
 * See .claude/rules/no-hallucinated-legal-data.md.
 *
 * Commands:
 *   npx tsx scripts/generate-case-law-enrichment.ts --missing-states                          # Generate ID + SC
 *   npx tsx scripts/generate-case-law-enrichment.ts --enrich --jurisdiction FL                 # Enrich single jurisdiction
 *   npx tsx scripts/generate-case-law-enrichment.ts --enrich --all                             # Enrich all jurisdictions
 *   npx tsx scripts/generate-case-law-enrichment.ts --full --all                               # Missing states + enrich all
 *   npx tsx scripts/generate-case-law-enrichment.ts --build-migration                          # Build SQL migration
 *   npx tsx scripts/generate-case-law-enrichment.ts --validate                                 # Validate output data
 *   npx tsx scripts/generate-case-law-enrichment.ts --stats                                    # Show statistics
 *   npx tsx scripts/generate-case-law-enrichment.ts --dry-run --enrich --jurisdiction FL       # Dry run
 *
 * Case law pipeline (VERIFIED SOURCES ONLY):
 *   node scripts/legal-research-all.mjs                                                        # Verify statutes
 *   node scripts/classify-case-law.mjs --limit 50                                              # Fetch+classify from CourtListener
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// Re-use COMMON_CHARGES and JURISDICTIONS from the existing taxonomy script
import { COMMON_CHARGES } from "./generate-charge-taxonomy.js";
import type { CommonChargeDefinition } from "./generate-charge-taxonomy.js";
// Claude Code session wrapper — runs under local `claude -p` CLI, no API credits.
import { callClaude } from "./lib/blog-gen/claude-client.mjs";

// ── Setup ────────────────────────────────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..");
const DATA_DIR = path.join(PROJECT_ROOT, "data", "charge-taxonomy");
const ENRICHMENT_DIR = path.join(DATA_DIR, "enrichment");
const CASE_LAW_DIR = path.join(DATA_DIR, "case-law");

// Load .env.local / .env
function loadEnvFile(filepath: string): void {
  if (!fs.existsSync(filepath)) return;
  const lines = fs.readFileSync(filepath, "utf-8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (!(key in process.env)) {
      process.env[key] = val;
    }
  }
}

loadEnvFile(path.join(PROJECT_ROOT, ".env.local"));
loadEnvFile(path.join(PROJECT_ROOT, ".env"));

// ── Types ────────────────────────────────────────────────────────────────────

interface JurisdictionStatute {
  common_charge_slug: string;
  statute_number: string;
  statute_title: string;
  offense_class: string;
  penalty_min: string | null;
  penalty_max: string;
  fine_max: string | null;
  elements: string[];
  mandatory_minimum: string | null;
  enhancements: string[];
  notes: string | null;
}

interface EnrichmentEntry {
  common_charge_slug: string;
  prosecution_strengths: string[];
  defense_opportunities: string[];
  common_defenses: string[];
}

// CaseLawEntry — read-only type for validation/stats of data produced by
// the VERIFIED pipeline (legal-research-all.mjs + classify-case-law.mjs).
// This script NEVER generates case law. See .claude/rules/no-hallucinated-legal-data.md.
interface CaseLawEntry {
  common_charge_slug: string;
  case_name: string;
  citation: string;
  court: string;
  year: number;
  holding: string;
  benefit_type: "prosecution" | "defense" | "both";
  significance: string;
}

// ── Jurisdiction List ─────────────────────────────────────────────────────────

const JURISDICTIONS: ReadonlyArray<{ code: string; name: string }> = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
  { code: "DC", name: "District of Columbia" },
  { code: "federal", name: "Federal (United States)" },
] as const;

const MISSING_STATES = ["ID", "SC"];

// ── Claude Code session (replaces direct Anthropic API) ────────────────────
// Uses callClaude subprocess wrapper: spawns `claude -p` under the local
// Claude Code session. Zero Anthropic API credits consumed.

async function callAnthropicAPI(
  prompt: string,
  _maxTokens: number = 16000
): Promise<string> {
  const result = await callClaude({ userPrompt: prompt });
  if (!result?.text) throw new Error("No text returned from claude -p");
  return result.text as string;
}


function stripMarkdownFences(raw: string): string {
  let s = raw.trim();
  if (s.startsWith("```")) {
    const firstNewline = s.indexOf("\n");
    const lastFence = s.lastIndexOf("```");
    if (firstNewline !== -1 && lastFence > firstNewline) {
      s = s.slice(firstNewline + 1, lastFence).trim();
    }
  }
  return s;
}

// ── File I/O ──────────────────────────────────────────────────────────────────

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function saveJSON(filepath: string, data: unknown): void {
  fs.writeFileSync(filepath, JSON.stringify(data, null, 2), "utf-8");
}

function loadJSON<T>(filepath: string): T {
  return JSON.parse(fs.readFileSync(filepath, "utf-8")) as T;
}

function jurisdictionFilePath(code: string): string {
  return path.join(DATA_DIR, `${code}.json`);
}

function enrichmentFilePath(code: string): string {
  return path.join(ENRICHMENT_DIR, `${code}.json`);
}

function caseLawFilePath(code: string): string {
  return path.join(CASE_LAW_DIR, `${code}.json`);
}

function delay(ms: number): Promise<void> {
  return new Promise<void>((resolve) => setTimeout(resolve, ms));
}

// ── SQL Escaping (split+join, no regex on content) ───────────────────────────

function escapeSqlSingleQuotes(val: string): string {
  return val.split("'").join("''");
}

function escapeSqlDoubleQuotes(val: string): string {
  return val.split('"').join('\\"');
}

function sqlStr(val: string | null): string {
  if (val === null || val === undefined) return "NULL";
  return "'" + escapeSqlSingleQuotes(val) + "'";
}

function sqlTextArray(arr: string[] | null | undefined): string {
  if (!arr || arr.length === 0) return "'{}'";
  const escaped = arr.map(
    (s) => '"' + escapeSqlDoubleQuotes(escapeSqlSingleQuotes(s)) + '"'
  );
  return "'{" + escaped.join(",") + "}'";
}

// ── Prompt Builders ───────────────────────────────────────────────────────────

function buildJurisdictionPrompt(code: string, name: string): string {
  const chargeList = COMMON_CHARGES.map(
    (c: CommonChargeDefinition) => `- ${c.slug}: ${c.label}`
  ).join("\n");

  return `You are a legal research assistant creating a criminal charge taxonomy database. For the jurisdiction of ${name} (${code}), provide the statute-specific information for each of the following common criminal charges.

For each charge, return a JSON object with:
- common_charge_slug: the slug from the list below
- statute_number: the specific statute number (e.g., "784.045" for FL, "PC 245(a)(1)" for CA)
- statute_title: official title of the statute
- offense_class: classification (e.g., "2nd Degree Felony", "Class A Misdemeanor")
- penalty_min: minimum penalty (e.g., "0 years" or null)
- penalty_max: maximum penalty (e.g., "15 years")
- fine_max: maximum fine (e.g., "$10,000")
- elements: array of prosecution elements (what must be proved)
- mandatory_minimum: specific mandatory minimum or null
- enhancements: array of applicable enhancements
- notes: jurisdiction-specific nuances (wobbler status, diversion eligibility, etc.)

OMIT any charge that does not exist as a distinct offense in this jurisdiction.

Return ONLY valid JSON — an array of objects. No markdown, no explanation.

Common charges to map:
${chargeList}`;
}

function buildEnrichmentPrompt(
  code: string,
  name: string,
  statutes: JurisdictionStatute[]
): string {
  const statuteList = statutes
    .map(
      (s) =>
        `- ${s.common_charge_slug}: ${s.statute_title} (${s.statute_number}) — ${s.offense_class}`
    )
    .join("\n");

  return `You are a criminal defense strategy analyst. For each statute in ${name} (${code}), provide a prosecution/defense benefit analysis.

For each statute below, return a JSON object with:
- common_charge_slug: the slug from the list
- prosecution_strengths: array of 3-5 typical prosecution advantages when bringing this charge (e.g., "Mandatory minimum limits plea bargaining leverage", "Multiple elements give prosecution charging flexibility")
- defense_opportunities: array of 3-5 strategic defense opportunities specific to this charge (e.g., "Elements require proving specific intent — creates reasonable doubt avenue", "Mandatory breath test challenge under implied consent statute")
- common_defenses: array of 3-5 recognized legal defenses for this charge (e.g., "Self-defense under § 776.012", "Lack of specific intent", "Entrapment")

Focus on ${name}-specific law, not generic defenses. Reference specific statutes, case law principles, and procedural rules where applicable. Each item should be a concise but specific statement (1-2 sentences max).

Return ONLY valid JSON — an array of objects. No markdown, no explanation.

Statutes to analyze:
${statuteList}`;
}

// ── Missing States ───────────────────────────────────────────────────────────

async function generateMissingStates(dryRun: boolean): Promise<void> {
  ensureDir(DATA_DIR);

  const toGenerate = MISSING_STATES.filter((code) => {
    const filepath = jurisdictionFilePath(code);
    if (fs.existsSync(filepath)) {
      console.log(`Skipping ${code} — JSON already exists`);
      return false;
    }
    return true;
  });

  if (toGenerate.length === 0) {
    console.log("All missing states already generated.");
    return;
  }

  console.log(
    `Generating ${toGenerate.length} missing state(s): ${toGenerate.join(", ")}`
  );

  for (let i = 0; i < toGenerate.length; i++) {
    const code = toGenerate[i];
    const jur = JURISDICTIONS.find((j) => j.code === code);
    if (!jur) {
      console.error(`Unknown jurisdiction code: ${code}`);
      continue;
    }

    console.log(`\nGenerating ${code} (${jur.name})... (${i + 1}/${toGenerate.length})`);
    const prompt = buildJurisdictionPrompt(jur.code, jur.name);

    if (dryRun) {
      console.log("\n--- DRY RUN: Prompt Preview ---");
      const preview =
        prompt.length > 2000
          ? prompt.slice(0, 2000) + `\n... [${prompt.length - 2000} more chars]`
          : prompt;
      console.log(preview);
      console.log(`\nTotal charges in prompt: ${COMMON_CHARGES.length}`);
      console.log("--- End of Prompt ---\n");
      continue;
    }

    try {
      const raw = await callAnthropicAPI(prompt);
      const jsonStr = stripMarkdownFences(raw);
      const parsed = JSON.parse(jsonStr) as JurisdictionStatute[];
      saveJSON(jurisdictionFilePath(code), parsed);
      console.log(`  Saved ${parsed.length} statutes for ${code}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(`  ERROR generating ${code}: ${message}`);
    }

    if (!dryRun && i < toGenerate.length - 1) {
      await delay(2000);
    }
  }

  console.log("\nMissing states generation complete.");
}

// ── Enrichment ───────────────────────────────────────────────────────────────

async function enrichJurisdiction(
  code: string,
  name: string,
  index: number,
  total: number,
  dryRun: boolean
): Promise<void> {
  console.log(`Enriching ${code} (${name})... (${index}/${total})`);

  const statutePath = jurisdictionFilePath(code);
  if (!fs.existsSync(statutePath)) {
    console.error(`  Skipping ${code} — no statute data at ${statutePath}`);
    return;
  }

  const statutes = loadJSON<JurisdictionStatute[]>(statutePath);
  if (!Array.isArray(statutes) || statutes.length === 0) {
    console.error(`  Skipping ${code} — empty or invalid statute data`);
    return;
  }

  // Process in batches of 25 to keep prompt size manageable
  const BATCH_SIZE = 25;
  const allEnrichments: EnrichmentEntry[] = [];

  for (let batchIdx = 0; batchIdx < statutes.length; batchIdx += BATCH_SIZE) {
    const batch = statutes.slice(batchIdx, batchIdx + BATCH_SIZE);
    const batchNum = Math.floor(batchIdx / BATCH_SIZE) + 1;
    const totalBatches = Math.ceil(statutes.length / BATCH_SIZE);

    if (totalBatches > 1) {
      console.log(
        `  Batch ${batchNum}/${totalBatches} (${batch.length} statutes)`
      );
    }

    const prompt = buildEnrichmentPrompt(code, name, batch);

    if (dryRun) {
      if (batchIdx === 0) {
        console.log("\n--- DRY RUN: Enrichment Prompt Preview ---");
        const preview =
          prompt.length > 2000
            ? prompt.slice(0, 2000) +
              `\n... [${prompt.length - 2000} more chars]`
            : prompt;
        console.log(preview);
        console.log(`\nStatutes in batch: ${batch.length}`);
        console.log("--- End of Prompt ---\n");
      }
      continue;
    }

    try {
      const raw = await callAnthropicAPI(prompt);
      const jsonStr = stripMarkdownFences(raw);
      const parsed = JSON.parse(jsonStr) as EnrichmentEntry[];
      allEnrichments.push(...parsed);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(
        `  ERROR enriching ${code} batch ${batchNum}: ${message}`
      );
    }

    if (!dryRun && batchIdx + BATCH_SIZE < statutes.length) {
      await delay(2000);
    }
  }

  if (!dryRun && allEnrichments.length > 0) {
    ensureDir(ENRICHMENT_DIR);
    saveJSON(enrichmentFilePath(code), allEnrichments);
    console.log(`  Saved ${allEnrichments.length} enrichment entries for ${code}`);
  }
}

async function enrichAll(dryRun: boolean): Promise<void> {
  const toProcess = JURISDICTIONS.filter(({ code }) => {
    const filepath = enrichmentFilePath(code);
    if (fs.existsSync(filepath)) {
      console.log(`Skipping ${code} enrichment — already exists`);
      return false;
    }
    // Must have statute data to enrich
    if (!fs.existsSync(jurisdictionFilePath(code))) {
      console.log(`Skipping ${code} enrichment — no statute data`);
      return false;
    }
    return true;
  });

  console.log(
    `\n${toProcess.length} jurisdictions to enrich (${JURISDICTIONS.length - toProcess.length} skipped)`
  );

  for (let i = 0; i < toProcess.length; i++) {
    const { code, name } = toProcess[i];
    await enrichJurisdiction(code, name, i + 1, toProcess.length, dryRun);
    if (!dryRun && i < toProcess.length - 1) {
      await delay(2000);
    }
  }

  console.log("\nEnrichment complete.");
}

async function enrichSingle(
  jurisdictionCode: string,
  dryRun: boolean
): Promise<void> {
  const upper = jurisdictionCode.toUpperCase();
  const jur =
    JURISDICTIONS.find((j) => j.code === upper) ??
    JURISDICTIONS.find(
      (j) => j.code.toLowerCase() === jurisdictionCode.toLowerCase()
    );

  if (!jur) {
    console.error(`Unknown jurisdiction: ${jurisdictionCode}`);
    console.error(
      `Valid codes: ${JURISDICTIONS.map((j) => j.code).join(", ")}`
    );
    process.exit(1);
  }

  ensureDir(ENRICHMENT_DIR);
  await enrichJurisdiction(jur.code, jur.name, 1, 1, dryRun);
}

// ── Case Law ─────────────────────────────────────────────────────────────────
// SAFETY: Case law is NEVER generated by this script.
// Case law MUST come from verified sources via the existing pipeline:
//   1. node scripts/legal-research-all.mjs    (verify statutes, find citing cases on CourtListener)
//   2. node scripts/classify-case-law.mjs     (fetch real opinions, classify defense/prosecution)
// See .claude/rules/no-hallucinated-legal-data.md

// ── Build Migration ──────────────────────────────────────────────────────────

function buildMigration(): void {
  const migrationDir = path.join(PROJECT_ROOT, "supabase", "migrations");
  ensureDir(migrationDir);

  // Find next migration number
  const existingMigrations = fs
    .readdirSync(migrationDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  const lastMigration = existingMigrations[existingMigrations.length - 1];
  const lastNum = lastMigration
    ? parseInt(lastMigration.split("_")[0], 10)
    : 30;
  const nextNum = String(lastNum + 1).padStart(
    lastMigration ? lastMigration.split("_")[0].length : 16,
    "0"
  );

  const migrationFile = path.join(
    migrationDir,
    `${nextNum}_enrichment-and-case-law-data.sql`
  );

  const lines: string[] = [];

  lines.push(
    `-- Migration: Add enrichment columns to jurisdiction_statutes + benefit_type to statute_case_law`
  );
  lines.push(`-- Generated by scripts/generate-case-law-enrichment.ts`);
  lines.push(`-- Date: ${new Date().toISOString().split("T")[0]}`);
  lines.push("");

  // ── Part 1: Schema changes
  lines.push(
    "-- ============================================================"
  );
  lines.push(
    "-- 1. Add enrichment columns to jurisdiction_statutes"
  );
  lines.push(
    "-- ============================================================"
  );
  lines.push("");
  lines.push("ALTER TABLE jurisdiction_statutes");
  lines.push(
    "  ADD COLUMN IF NOT EXISTS prosecution_strengths text[] DEFAULT '{}',"
  );
  lines.push(
    "  ADD COLUMN IF NOT EXISTS defense_opportunities text[] DEFAULT '{}',"
  );
  lines.push(
    "  ADD COLUMN IF NOT EXISTS common_defenses text[] DEFAULT '{}';"
  );
  lines.push("");

  // ── Part 1b: Add benefit_type to statute_case_law
  lines.push(
    "-- ============================================================"
  );
  lines.push(
    "-- 2. Add benefit_type column to statute_case_law"
  );
  lines.push(
    "-- ============================================================"
  );
  lines.push("");
  lines.push("ALTER TABLE statute_case_law");
  lines.push(
    "  ADD COLUMN IF NOT EXISTS benefit_type text DEFAULT 'both';"
  );
  lines.push("");

  // ── Part 2: Enrichment data UPDATEs
  lines.push(
    "-- ============================================================"
  );
  lines.push(
    "-- 3. Enrichment data (prosecution/defense analysis)"
  );
  lines.push(
    "-- ============================================================"
  );
  lines.push("");

  let enrichmentCount = 0;
  for (const { code } of JURISDICTIONS) {
    const filepath = enrichmentFilePath(code);
    if (!fs.existsSync(filepath)) continue;

    let entries: EnrichmentEntry[];
    try {
      entries = loadJSON<EnrichmentEntry[]>(filepath);
    } catch {
      console.error(`  Skipping enrichment for ${code} — invalid JSON`);
      continue;
    }

    if (!Array.isArray(entries) || entries.length === 0) continue;

    lines.push(`-- ${code} enrichment`);
    for (const entry of entries) {
      const prosArr = sqlTextArray(entry.prosecution_strengths);
      const defOppArr = sqlTextArray(entry.defense_opportunities);
      const defArr = sqlTextArray(entry.common_defenses);

      lines.push(`UPDATE jurisdiction_statutes SET`);
      lines.push(`  prosecution_strengths = ${prosArr},`);
      lines.push(`  defense_opportunities = ${defOppArr},`);
      lines.push(`  common_defenses = ${defArr}`);
      lines.push(
        `WHERE common_charge_slug = ${sqlStr(entry.common_charge_slug)} AND jurisdiction = ${sqlStr(code)};`
      );
      lines.push("");
      enrichmentCount++;
    }
  }

  // ── Part 3: NO CASE LAW INSERTS ──
  // SAFETY: Case law is NEVER inserted from local files. Per the
  // no-hallucinated-legal-data rule, case law must come from CourtListener
  // via legal-research-all.mjs + classify-case-law.mjs. This script writes
  // ONLY enrichment (prosecution/defense strategic analysis) — never citations.
  lines.push(
    "-- ============================================================"
  );
  lines.push(
    "-- 4. Case law: NOT INSERTED HERE"
  );
  lines.push(
    "-- ============================================================"
  );
  lines.push("-- Case law comes ONLY from verified CourtListener sources via:");
  lines.push("--   node scripts/legal-research-all.mjs");
  lines.push("--   node scripts/classify-case-law.mjs");
  lines.push("-- See .claude/rules/no-hallucinated-legal-data.md");
  lines.push("");

  const sql = lines.join("\n");
  fs.writeFileSync(migrationFile, sql, "utf-8");

  console.log(`\nMigration written to: ${migrationFile}`);
  console.log(`  Enrichment UPDATEs : ${enrichmentCount}`);
  console.log(`  Case law INSERTs   : 0 (safety: verified sources only)`);
}

// ── Validation ───────────────────────────────────────────────────────────────

function validateOutput(): void {
  let totalErrors = 0;

  console.log("=== Validating Statute Data ===\n");

  const missingStatutes: string[] = [];
  for (const { code } of JURISDICTIONS) {
    if (!fs.existsSync(jurisdictionFilePath(code))) {
      missingStatutes.push(code);
    }
  }
  if (missingStatutes.length > 0) {
    console.log(
      `  Missing statute files: ${missingStatutes.join(", ")}`
    );
    totalErrors += missingStatutes.length;
  } else {
    console.log("  All 52 jurisdiction statute files present.");
  }

  console.log("\n=== Validating Enrichment Data ===\n");

  const ENRICHMENT_FIELDS: ReadonlyArray<keyof EnrichmentEntry> = [
    "prosecution_strengths",
    "defense_opportunities",
    "common_defenses",
  ];

  let enrichmentFiles = 0;
  let enrichmentEntries = 0;
  let enrichmentErrors = 0;

  for (const { code } of JURISDICTIONS) {
    const filepath = enrichmentFilePath(code);
    if (!fs.existsSync(filepath)) continue;

    enrichmentFiles++;
    let entries: EnrichmentEntry[];
    try {
      entries = loadJSON<EnrichmentEntry[]>(filepath);
    } catch {
      console.error(`  ${code}: INVALID JSON in enrichment file`);
      enrichmentErrors++;
      continue;
    }

    if (!Array.isArray(entries)) {
      console.error(`  ${code}: Enrichment data is not an array`);
      enrichmentErrors++;
      continue;
    }

    enrichmentEntries += entries.length;

    for (const entry of entries) {
      for (const field of ENRICHMENT_FIELDS) {
        const val = entry[field];
        if (!Array.isArray(val) || val.length === 0) {
          console.error(
            `  ${code}/${entry.common_charge_slug}: Empty ${field}`
          );
          enrichmentErrors++;
        }
      }
    }
  }

  console.log(`  Enrichment files   : ${enrichmentFiles}/52`);
  console.log(`  Enrichment entries : ${enrichmentEntries}`);
  console.log(`  Enrichment errors  : ${enrichmentErrors}`);
  totalErrors += enrichmentErrors;

  console.log("\n=== Validating Case Law Data ===\n");

  const CASE_LAW_REQUIRED: ReadonlyArray<keyof CaseLawEntry> = [
    "case_name",
    "citation",
    "court",
    "year",
    "holding",
    "benefit_type",
    "significance",
  ];

  let caseLawFiles = 0;
  let caseLawEntries = 0;
  let caseLawErrors = 0;

  for (const { code } of JURISDICTIONS) {
    const filepath = caseLawFilePath(code);
    if (!fs.existsSync(filepath)) continue;

    caseLawFiles++;
    let entries: CaseLawEntry[];
    try {
      entries = loadJSON<CaseLawEntry[]>(filepath);
    } catch {
      console.error(`  ${code}: INVALID JSON in case law file`);
      caseLawErrors++;
      continue;
    }

    if (!Array.isArray(entries)) {
      console.error(`  ${code}: Case law data is not an array`);
      caseLawErrors++;
      continue;
    }

    caseLawEntries += entries.length;

    // Check coverage: each statute should have 3-5 cases
    const statutePath = jurisdictionFilePath(code);
    if (fs.existsSync(statutePath)) {
      const statutes = loadJSON<JurisdictionStatute[]>(statutePath);
      const casesBySlug = new Map<string, number>();
      for (const e of entries) {
        casesBySlug.set(
          e.common_charge_slug,
          (casesBySlug.get(e.common_charge_slug) ?? 0) + 1
        );
      }
      for (const s of statutes) {
        const count = casesBySlug.get(s.common_charge_slug) ?? 0;
        if (count === 0) {
          console.error(
            `  ${code}/${s.common_charge_slug}: No case law entries`
          );
          caseLawErrors++;
        }
      }
    }

    for (const entry of entries) {
      for (const field of CASE_LAW_REQUIRED) {
        const val = entry[field];
        if (val === null || val === undefined || val === "") {
          console.error(
            `  ${code}/${entry.common_charge_slug}: Missing ${field} in "${entry.case_name || "unknown"}"`
          );
          caseLawErrors++;
        }
      }

      if (
        entry.benefit_type &&
        !["prosecution", "defense", "both"].includes(entry.benefit_type)
      ) {
        console.error(
          `  ${code}/${entry.common_charge_slug}: Invalid benefit_type "${entry.benefit_type}" in "${entry.case_name}"`
        );
        caseLawErrors++;
      }
    }
  }

  console.log(`  Case law files     : ${caseLawFiles}/52`);
  console.log(`  Case law entries   : ${caseLawEntries}`);
  console.log(`  Case law errors    : ${caseLawErrors}`);
  totalErrors += caseLawErrors;

  console.log(`\n=== Validation Summary ===`);
  console.log(`  Total errors: ${totalErrors}`);

  if (totalErrors > 0) process.exit(1);
}

// ── Stats ────────────────────────────────────────────────────────────────────

function showStats(): void {
  console.log("=== Charge Taxonomy Statistics ===\n");

  // Statutes
  let totalStatutes = 0;
  let statuteFiles = 0;
  const statuteCoverage: Array<{ code: string; count: number }> = [];

  for (const { code } of JURISDICTIONS) {
    const filepath = jurisdictionFilePath(code);
    if (!fs.existsSync(filepath)) continue;
    statuteFiles++;
    try {
      const data = loadJSON<JurisdictionStatute[]>(filepath);
      totalStatutes += data.length;
      statuteCoverage.push({ code, count: data.length });
    } catch {
      /* skip invalid */
    }
  }

  console.log(`Statute Data:`);
  console.log(`  Jurisdictions with data : ${statuteFiles}/52`);
  console.log(`  Total statutes          : ${totalStatutes}`);
  if (statuteCoverage.length > 0) {
    const avg = Math.round(totalStatutes / statuteCoverage.length);
    const min = Math.min(...statuteCoverage.map((s) => s.count));
    const max = Math.max(...statuteCoverage.map((s) => s.count));
    console.log(`  Avg per jurisdiction    : ${avg}`);
    console.log(`  Min                     : ${min}`);
    console.log(`  Max                     : ${max}`);
  }

  // Missing
  const missingStatutes = JURISDICTIONS.filter(
    ({ code }) => !fs.existsSync(jurisdictionFilePath(code))
  ).map(({ code }) => code);
  if (missingStatutes.length > 0) {
    console.log(`  Missing                 : ${missingStatutes.join(", ")}`);
  }

  // Enrichment
  let totalEnrichment = 0;
  let enrichmentFilesCount = 0;

  for (const { code } of JURISDICTIONS) {
    const filepath = enrichmentFilePath(code);
    if (!fs.existsSync(filepath)) continue;
    enrichmentFilesCount++;
    try {
      const data = loadJSON<EnrichmentEntry[]>(filepath);
      totalEnrichment += data.length;
    } catch {
      /* skip */
    }
  }

  console.log(`\nEnrichment Data:`);
  console.log(`  Jurisdictions enriched  : ${enrichmentFilesCount}/52`);
  console.log(`  Total enrichment entries: ${totalEnrichment}`);

  // Case Law
  let totalCaseLaw = 0;
  let caseLawFileCount = 0;
  let prosecutionCount = 0;
  let defenseCount = 0;
  let bothCount = 0;

  for (const { code } of JURISDICTIONS) {
    const filepath = caseLawFilePath(code);
    if (!fs.existsSync(filepath)) continue;
    caseLawFileCount++;
    try {
      const data = loadJSON<CaseLawEntry[]>(filepath);
      totalCaseLaw += data.length;
      for (const entry of data) {
        if (entry.benefit_type === "prosecution") prosecutionCount++;
        else if (entry.benefit_type === "defense") defenseCount++;
        else bothCount++;
      }
    } catch {
      /* skip */
    }
  }

  console.log(`\nCase Law Data:`);
  console.log(`  Jurisdictions with cases: ${caseLawFileCount}/52`);
  console.log(`  Total case law entries  : ${totalCaseLaw}`);
  if (caseLawFileCount > 0) {
    console.log(`  WARNING: case-law/ should be empty — case law belongs in DB only.`);
    console.log(`  Files here may be hallucinated. Run the watcher and delete.`);
  }

  // Estimated totals at completion
  console.log(`\nProjected at Full Completion:`);
  const avgStatutesPerJur =
    statuteCoverage.length > 0
      ? Math.round(totalStatutes / statuteCoverage.length)
      : 80;
  console.log(
    `  Est. total statutes     : ~${52 * avgStatutesPerJur}`
  );
  console.log(
    `  Est. enrichment entries : ~${52 * avgStatutesPerJur}`
  );
  console.log(
    `  Case law entries        : populated by legal-research-all.mjs (CourtListener), not this script`
  );
}

// ── CLI ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const hasFlag = (flag: string): boolean => args.includes(flag);
  const getFlagValue = (flag: string): string | null => {
    const idx = args.indexOf(flag);
    return idx !== -1 && idx + 1 < args.length ? (args[idx + 1] ?? null) : null;
  };

  const dryRun = hasFlag("--dry-run");
  const jurisdictionCode = getFlagValue("--jurisdiction");
  const all = hasFlag("--all");

  if (hasFlag("--stats")) {
    showStats();
    return;
  }

  if (hasFlag("--validate")) {
    validateOutput();
    return;
  }

  if (hasFlag("--build-migration")) {
    buildMigration();
    return;
  }

  if (hasFlag("--missing-states")) {
    await generateMissingStates(dryRun);
    return;
  }

  if (hasFlag("--enrich")) {
    if (all) {
      await enrichAll(dryRun);
    } else if (jurisdictionCode) {
      await enrichSingle(jurisdictionCode, dryRun);
    } else {
      console.error("--enrich requires --all or --jurisdiction <CODE>");
      process.exit(1);
    }
    return;
  }

  if (hasFlag("--case-law")) {
    console.log("SAFETY: Case law is NEVER generated by this script.");
    console.log("Case law MUST come from verified sources (CourtListener API).\n");
    console.log("Use the verified pipeline instead:");
    console.log("  node scripts/legal-research-all.mjs          # Verify statutes + find citing cases");
    console.log("  node scripts/classify-case-law.mjs --limit 50 # Fetch+classify real opinions\n");
    console.log("See .claude/rules/no-hallucinated-legal-data.md");
    process.exit(1);
  }

  if (hasFlag("--full")) {
    if (!all && !jurisdictionCode) {
      console.error("--full requires --all or --jurisdiction <CODE>");
      process.exit(1);
    }

    if (all) {
      console.log("=== FULL RUN: All jurisdictions ===\n");
      console.log("Step 1/2: Missing states...");
      await generateMissingStates(dryRun);
      console.log("\nStep 2/2: Enrichment...");
      await enrichAll(dryRun);
    } else if (jurisdictionCode) {
      console.log(`=== FULL RUN: ${jurisdictionCode} ===\n`);

      const upper = jurisdictionCode.toUpperCase();
      if (MISSING_STATES.includes(upper)) {
        console.log("Step 1/2: Generate missing statute data...");
        await generateMissingStates(dryRun);
      } else {
        console.log("Step 1/2: Statute data already exists — skipping.");
      }

      console.log("\nStep 2/2: Enrichment...");
      await enrichSingle(jurisdictionCode, dryRun);
    }

    if (!dryRun) {
      console.log("\n=== Full run complete. Run --build-migration to create SQL. ===");
      console.log("For case law: node scripts/legal-research-all.mjs + node scripts/classify-case-law.mjs");
    }
    return;
  }

  // Default: usage
  console.log(`
Case Law Enrichment Script
============================
Usage:

  Missing States (ID, SC):
    npx tsx scripts/generate-case-law-enrichment.ts --missing-states
    npx tsx scripts/generate-case-law-enrichment.ts --dry-run --missing-states

  Enrichment (prosecution/defense analysis):
    npx tsx scripts/generate-case-law-enrichment.ts --enrich --jurisdiction FL
    npx tsx scripts/generate-case-law-enrichment.ts --enrich --all

  Case Law (VERIFIED SOURCES ONLY — never generated):
    node scripts/legal-research-all.mjs          # Verify statutes + find citing cases on CourtListener
    node scripts/classify-case-law.mjs --limit 50 # Fetch+classify real opinions from CourtListener

  Full Pipeline (missing states + enrichment only):
    npx tsx scripts/generate-case-law-enrichment.ts --full --all
    npx tsx scripts/generate-case-law-enrichment.ts --full --jurisdiction FL

  Build Migration:
    npx tsx scripts/generate-case-law-enrichment.ts --build-migration

  Validate & Stats:
    npx tsx scripts/generate-case-law-enrichment.ts --validate
    npx tsx scripts/generate-case-law-enrichment.ts --stats

  All commands support --dry-run to preview prompts without API calls.

Stats:
  Common charges    : ${COMMON_CHARGES.length}
  Jurisdictions     : ${JURISDICTIONS.length}
  Missing states    : ${MISSING_STATES.join(", ")}
  Output dirs       : data/charge-taxonomy/enrichment/
                      data/charge-taxonomy/case-law/
`);
}

main().catch((err: unknown) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
