-- TICKET-10: Doctrine extraction over CourtListener opinion bodies
--
-- Creates doctrine_opinion_quotes (NEW table; preserves existing
-- doctrine_quotes which is a transcript-matching surface with a
-- different schema). Each row is one doctrine match in one opinion
-- body, with the surrounding ±400 chars stored verbatim.
--
-- Wire targets (Tier 9 / IB / X-Ray / Charge Authority Pack):
--   getDoctrineSpotlights(state, charge_slug?, top_n=3)
--     -> top-N rows ordered by relevance_score DESC
--
-- Anti-hallucination invariant (no-hallucinated-legal-data.md):
--   Every row stores quote_text VERBATIM from cl_opinion_bodies.plain_text
--   plus source_url pointing at the CourtListener cluster page. Rows
--   without both are rejected at extractor-level.

CREATE TABLE IF NOT EXISTS doctrine_opinion_quotes (
  id BIGSERIAL PRIMARY KEY,
  opinion_id BIGINT NOT NULL,
  cluster_id BIGINT NOT NULL,

  -- Doctrine taxonomy slug (e.g. 'reasonable-suspicion'). See
  -- src/lib/doctrines/taxonomy.ts for the canonical 30-doctrine seed.
  doctrine_slug TEXT NOT NULL,

  -- Charge slug (e.g. 'fl-dui'). Nullable in v1 -- v2 adds the
  -- doctrine -> charge mapping pass via charge_taxonomy joins.
  charge_slug TEXT,

  -- CourtListener jurisdiction code: F, FD, FB, FBP, S, SA, ST.
  jurisdiction TEXT,

  -- CourtListener court_id slug (e.g. 'nysd', 'ind', 'wash').
  court_id TEXT,

  -- US state postal code derived from court_id (e.g. 'NY', 'IN', 'WA').
  -- Nullable for federal-only courts that don't map to a single state
  -- (e.g. 'scotus', 'cafc'). Indexed for the spotlight query.
  state_code TEXT,

  -- Verbatim quote: ±400 chars surrounding the doctrine match.
  -- NEVER null. NEVER paraphrased. Anti-hallucination invariant.
  quote_text TEXT NOT NULL,

  -- Char offset of the doctrine term in the original plain_text.
  quote_offset INT NOT NULL,

  -- Number of doctrine matches in this opinion (extracted at scan time).
  doctrine_match_count INT NOT NULL DEFAULT 1,

  -- Citation count of this opinion's CLUSTER (not opinion). Pulled
  -- from cl_opinion_clusters.citation_count at extract time.
  citation_count INT NOT NULL DEFAULT 0,

  -- relevance = doctrine_match_count * (citation_count + 1)
  -- The +1 keeps un-cited opinions from collapsing to 0 score
  -- so single-citation matches still rank above zero-citation ones.
  relevance_score REAL NOT NULL,

  -- Verification URL -- CourtListener cluster page.
  source_url TEXT NOT NULL,

  -- Sha1 of quote_text for dedup across re-runs.
  quote_sha1 TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Hot-path index for getDoctrineSpotlights(state, charge_slug, top_n).
-- The (doctrine_slug, state_code) prefix supports state-scoped lookup;
-- relevance_score DESC supports top-N without sort spill.
CREATE INDEX IF NOT EXISTS idx_doctrine_opinion_quotes_lookup
  ON doctrine_opinion_quotes (doctrine_slug, state_code, relevance_score DESC);

-- Charge-scoped lookup for v2 (when charge_slug populated).
CREATE INDEX IF NOT EXISTS idx_doctrine_opinion_quotes_charge
  ON doctrine_opinion_quotes (doctrine_slug, charge_slug, state_code, relevance_score DESC)
  WHERE charge_slug IS NOT NULL;

-- Per-opinion lookup for re-extraction / dedup.
CREATE INDEX IF NOT EXISTS idx_doctrine_opinion_quotes_opinion
  ON doctrine_opinion_quotes (opinion_id);

CREATE INDEX IF NOT EXISTS idx_doctrine_opinion_quotes_cluster
  ON doctrine_opinion_quotes (cluster_id);

-- Dedup constraint: one row per (opinion_id, doctrine_slug, quote_sha1).
-- Re-extraction with the same input produces the same sha1 -> idempotent.
CREATE UNIQUE INDEX IF NOT EXISTS uq_doctrine_opinion_quotes_dedup
  ON doctrine_opinion_quotes (opinion_id, doctrine_slug, quote_sha1);

-- RLS: service-role only (this is a research surface, not customer-writable).
ALTER TABLE doctrine_opinion_quotes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_all" ON doctrine_opinion_quotes;
CREATE POLICY "service_role_all" ON doctrine_opinion_quotes
  TO service_role USING (true) WITH CHECK (true);

-- Authenticated read (for IB / X-Ray render path that runs as the
-- order's service-role-issued JWT but renders client-side fallback).
DROP POLICY IF EXISTS "authenticated_read" ON doctrine_opinion_quotes;
CREATE POLICY "authenticated_read" ON doctrine_opinion_quotes
  FOR SELECT TO authenticated USING (true);

COMMENT ON TABLE doctrine_opinion_quotes IS
  'TICKET-10 doctrine extraction. One row per doctrine match in a CourtListener opinion body. Verbatim quote + source_url enforced via NOT NULL. Distinct from doctrine_quotes (transcript-matching surface). Generated by scripts/extract-doctrine-quotes.mjs.';
